# Generated by Django 2.0.7 on 2018-08-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalservices',
            name='Photo',
            field=models.FileField(null='TRUE', upload_to=''),
        ),
    ]
