# Generated by Django 2.0.7 on 2018-08-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20180801_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalservices',
            name='Photo',
        ),
    ]
