# Generated by Django 2.0.7 on 2018-08-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_medicalservices_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('Nationality', models.CharField(choices=[('SA', 'Saudi'), ('PA', 'Pakistani'), ('IR', 'Iranian')], default='', max_length=2)),
                ('Photo', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='medicalservices',
            name='Photo',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='lost',
            name='Location',
            field=models.ForeignKey(on_delete='CASCAD', to='page.MedicalServices'),
        ),
    ]
