# Generated by Django 2.0.7 on 2018-08-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20180801_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='lost',
            name='Age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
