# Generated by Django 2.0.7 on 2018-08-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_lost_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalservices',
            name='Injury',
            field=models.CharField(choices=[('H', 'Head'), ('C', 'Chest'), ('S', 'Stomach'), ('D', 'Hands'), ('L', 'Legs')], default='', max_length=1),
        ),
    ]
