# Generated by Django 2.0.7 on 2018-08-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_medicalservices_injury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost',
            name='Location',
        ),
    ]
